// frontend/src/layouts/PublicLayout.tsx
import type { ReactNode } from 'react'

import { Navigate } from 'react-router'

import { useAuth } from '../hooks/useAuth'

type PublicLayoutProps = Readonly<{
  children: ReactNode
}>

/**
 * 公開レイアウト（未認証のみ）
 * - 認証済み: /へリダイレクト
 * - 未認証: childrenを表示
 */
export const PublicLayout = ({ children }: PublicLayoutProps) => {
  const { authState } = useAuth()

  switch (authState.status) {
    case 'loading':
      return <div className="flex items-center justify-center min-h-screen text-gray-600">Loading...</div>
    case 'authenticated':
      return <Navigate to="/" replace />
    case 'unauthenticated':
      return <>{children}</>
  }
}

// frontend/src/layouts/PublicLayout.vue
<script setup lang="ts">
import { useAuthStore } from '../stores/auth'

const authStore = useAuthStore()
</script>

<template>
  <div v-if="authStore.authState.status === 'loading'" class="flex items-center justify-center min-h-screen text-gray-600">
    Loading...
  </div>
  <slot v-else />
</template>
